// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\domain\audit\auditor.go

// Package auditor is a generated GoMock package.
package auditor

import (
	reflect "reflect"

	audit "github.com/dmitastr/yp_observability_service/internal/domain/audit"
	data "github.com/dmitastr/yp_observability_service/internal/domain/audit/data"
	listener "github.com/dmitastr/yp_observability_service/internal/domain/audit/listener"
	gomock "github.com/golang/mock/gomock"
)

// MockIAuditor is a mock of IAuditor interface.
type MockIAuditor struct {
	ctrl     *gomock.Controller
	recorder *MockIAuditorMockRecorder
}

// MockIAuditorMockRecorder is the mock recorder for MockIAuditor.
type MockIAuditorMockRecorder struct {
	mock *MockIAuditor
}

// NewMockIAuditor creates a new mock instance.
func NewMockIAuditor(ctrl *gomock.Controller) *MockIAuditor {
	mock := &MockIAuditor{ctrl: ctrl}
	mock.recorder = &MockIAuditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuditor) EXPECT() *MockIAuditorMockRecorder {
	return m.recorder
}

// AddListener mocks base method.
func (m *MockIAuditor) AddListener(arg0 listener.IListener) audit.IAuditor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddListener", arg0)
	ret0, _ := ret[0].(audit.IAuditor)
	return ret0
}

// AddListener indicates an expected call of AddListener.
func (mr *MockIAuditorMockRecorder) AddListener(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddListener", reflect.TypeOf((*MockIAuditor)(nil).AddListener), arg0)
}

// Notify mocks base method.
func (m *MockIAuditor) Notify(arg0 *data.Data) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockIAuditorMockRecorder) Notify(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockIAuditor)(nil).Notify), arg0)
}
