// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/client/client.go

// Package client is a generated GoMock package.
package client

import (
	reflect "reflect"

	models "github.com/dmitastr/yp_observability_service/internal/agent/models"
	gomock "github.com/golang/mock/gomock"
	context "golang.org/x/net/context"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close), arg0)
}

// SendMetric mocks base method.
func (m *MockClient) SendMetric(arg0 context.Context, arg1 models.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMetric", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMetric indicates an expected call of SendMetric.
func (mr *MockClientMockRecorder) SendMetric(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMetric", reflect.TypeOf((*MockClient)(nil).SendMetric), arg0, arg1)
}

// SendMetricsBatch mocks base method.
func (m *MockClient) SendMetricsBatch(arg0 context.Context, arg1 []models.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMetricsBatch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMetricsBatch indicates an expected call of SendMetricsBatch.
func (mr *MockClientMockRecorder) SendMetricsBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMetricsBatch", reflect.TypeOf((*MockClient)(nil).SendMetricsBatch), arg0, arg1)
}
